### ISSUE TITLE
casus point in wrong direction

### ISSUE THREAD

**Issue by rmm-fcul** [assisi/arena-ui#49]
The indicator on each CASU in the currently installed array points to the right.  A manual check shows that the "F" sensor points downwards.

```
1-2-3  ||
4-5-6  ||
7-8-9  \/
      Front
```

not sure whether this is a local configuration or a built-in layout.  How do we display in accurate orientation?

**Comment by stribor14** [comment]
My guess is that Yaw angle parameter in .arena file wasn't set correctly (in this case yaw should be -90° or -pi/2).

Easy fix would be writing 90 for that CASU in .arena file, but currently there are more issues with yaw angle (simulator reads yaw in radians, UI in degrees + different orientation, one is cw, other ccw).

I'll keep you updated on the fix here.

**Comment by stribor14** [comment]
It is now fixed in commit a808508
It should be pulled in main project on next pull request. Yaw angle in .arena file should be in radians with CCW sense or rotation. Graphical elements are also fixed according to this change.

EDIT:  IR sensors names in TreeView are fixed accordingly to CCW rotation in commit 3589246

![screenshot from 2016-08-12 14 01 50](https://cloud.githubusercontent.com/assets/10760409/17621886/ea5622cc-6096-11e6-933f-0365bb2243da.png)
