### ISSUE TITLE
Context menu ungroup

### ISSUE THREAD

**Issue by marselap** [assisi/arena-ui#94]
Ungroup option unavailable in context menu. ctrl+u works.

**Comment by rmm-fcul** [comment]
is this fix already in a released version of the ui?

The master workstation still has this problem. The version installed is shown below
> assisi@assisi:~$ dpkg -s assisi-arena-ui
> Package: assisi-arena-ui
> Status: install ok installed
> Architecture: amd64
> Version: 0.16.2-0ubuntu1~xenial1
>

**Comment by dmiklic** [comment]
This is fixed in 0.16.3, which has not been released yet. However, if `Ctrl+u` works, I don't consider this a major issue. 

The release of 0.16.3. on Xenial is planned by the end of June.

**Comment by rmm-fcul** [comment]
ok, the reason I asked is because when I tried this mentioned workaround (pressing `ctrl-u`) the gui crashed.  I didn't see it worth investigating further if new fixes have already been included in this part of the code; will just wait for the update (and try to get the right groups to start with ;)
