### ISSUE TITLE
Add keyboard shortcuts for setpoint dialogs

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#97]
Should be straightforward (just a call to setShortcut) but is not working, maybe due to [this bug](http://stackoverflow.com/questions/23916623/qt5-doesnt-recognised-shortcuts-unless-actions-are-added-to-a-toolbar)

**Comment by stribor14** [comment]
This bug is partially related.
First problems was QAction was defined when constructing context menu and we wanted to call it from parent before it even existed. With 1st bug-fix from link, shortcuts would work only when context menu is opened (and actions created).

Actions should be initialized in main window constructor.
